Examples/DemoApp/Models/ImportDuty.cs
namespace DemoApp.Models
{
    public class ImportDuty : Tax
    {
        protected override decimal CalculateTax(decimal price)
        {
            return price * 0.05m;
        }
    }
}

Examples/DemoApp/Models/Product.cs
namespace DemoApp.Models
{
    using System.Collections.Generic;
    using System.Linq;

    public class Product
    {
        private readonly List<Tax> taxes;

        public Product(int id, string name, decimal price, IEnumerable<Tax> taxes)
        {
            this.Id = id;
            this.Name = name;
            this.Price = price;
            this.taxes = taxes.ToList();
        }

        public int Id { get; private set; }

        public string Name { get; private set; }

        public decimal Price { get; private set; }

        public decimal GetTax()
        {
            return this.taxes.Sum(x => x.GetTaxAmount(this.Price));
        }

        public decimal GetTotalPrice()
        {
            return this.Price + this.GetTax();
        }
    }
}

Examples/DemoApp/Models/Receipt.cs
namespace DemoApp.Models
{
    using System.Collections.Generic;
    using System.Linq;

    public class Receipt
    {
        private readonly List<ReceiptItem> receiptItems;

        public Receipt(IEnumerable<Product> products)
        {
            var productsList = products.ToList();
            this.receiptItems = productsList.Select(x => new ReceiptItem { Name = x.Name, NetPrice = x.Price, Taxes = x.GetTax(), TotalPrice = x.GetTotalPrice() }).ToList();
            this.SalesTaxes = productsList.Sum(x => x.GetTax());
            this.TotalPrice = this.receiptItems.Sum(x => x.TotalPrice);
        }

        public IEnumerable<ReceiptItem> ReceiptItems
        {
            get
            {
                return this.receiptItems;
            }
        } 

        public decimal TotalPrice { get; private set; }

        public decimal SalesTaxes { get; private set; }
    }
}

Examples/DemoApp/Models/ReceiptItem.cs
namespace DemoApp.Models
{
    public class ReceiptItem
    {
        public string Name { get; set; }

        public decimal NetPrice { get; set; }

        public decimal Taxes { get; set; }

        public decimal TotalPrice { get; set; }
    }
}

Examples/DemoApp/Models/SalesTax.cs
namespace DemoApp.Models
{
    public class SalesTax : Tax
    {
        protected override decimal CalculateTax(decimal price)
        {
            return price * 0.1m;
        }
    }
}

Examples/DemoApp/Models/Tax.cs
namespace DemoApp.Models
{
    using System;

    public abstract class Tax
    {
        public decimal GetTaxAmount(decimal price)
        {
            return RoundTax(this.CalculateTax(price));
        }

        protected abstract decimal CalculateTax(decimal price);

        private static decimal RoundTax(decimal tax)
        {
            return Math.Round(tax * 20) / 20;
        }
    }
}

Examples/DemoApp/Controllers/BasketController.cs
namespace DemoApp.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using DemoApp.Infrastructure;
    using DemoApp.Models;

    public class BasketController : Controller
    {
        private readonly ProductRepository productRepository;

        public BasketController()
        {
            this.productRepository = new ProductRepository();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var basket = Basket.Current;
            var receipt = new Receipt(basket);

            return this.View(receipt);
        }

        [HttpPost]
        public ActionResult Add(int productId)
        {
            var product = this.productRepository.ById(productId);
            Basket.Current.Add(product);

            return this.Redirect(this.HttpContext.Request.UrlReferrer.ToString());
        }

        [HttpPost]
        public ActionResult Empty()
        {
             Basket.Current.Clear();

            return this.Redirect(this.HttpContext.Request.UrlReferrer.ToString());
        }

        [HttpGet]
        public ViewResult Summary()
        {
            var basket = Basket.Current;

            this.ViewBag.ItemCount = basket.Count;
            this.ViewBag.TotalPrice = basket.Sum(x => x.GetTotalPrice());

            return this.View();
        }
    }
}

Examples/DemoApp/Controllers/HomeController.cs
namespace DemoApp.Controllers
{
    using System.Web.Mvc;

    using DemoApp.Infrastructure;

    public class HomeController : Controller
    {
        private ProductRepository productRepository;

        public HomeController()
        {
            this.productRepository = new ProductRepository();
        }

        public ActionResult Index()
        {
            this.ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";
            this.ViewBag.Products = this.productRepository.All();

            return this.View();
        }
    }
}

Examples/DemoApp/Views/Basket/Index.cshtml
@model DemoApp.Models.Receipt
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
            </hgroup>
        </div>
    </section>
}
<h3>Your basket:</h3>
    
    @if (this.Model.ReceiptItems.Count() > 0)
    {
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price (excl. taxes)</th>
                    <th>Taxes</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in this.Model.ReceiptItems)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.NetPrice.ToString("c")</td>
                        <td>@item.Taxes.ToString("c")</td>
                        <td>@item.TotalPrice.ToString("c")</td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>Total</th>
                    <th></th>
                    <th>@this.Model.SalesTaxes.ToString("c")</th>
                    <th>@this.Model.TotalPrice.ToString("c")</th>
                </tr>
            </tfoot>
        </table>
        <p>
            @using (Html.BeginForm("Empty", "Basket", FormMethod.Post))
            {
                <button type="submit">Empty basket</button>
            }
        </p>
    }
    else
    {
        <p>Your basket is empty.</p>
    }

Examples/DemoApp/Views/Basket/Summary.cshtml
@{
    Layout = null;
}<div>
    @ViewBag.ItemCount item(s), total price @ViewBag.TotalPrice.ToString("c")
</div>

Examples/DemoApp/Views/Home/Index.cshtml
@using DemoApp.Models
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
            </hgroup>
        </div>
    </section>
}
<h3>Some products:</h3>
<ul class="round">

    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Product product in ViewBag.Products)
            {
                <tr>
                    <td>@product.Name</td>
                    <td>@product.GetTotalPrice().ToString("c")</td>
                    <td>
                        @using (Html.BeginForm("Add", "Basket", FormMethod.Post))
                        {
                            @Html.Hidden("productId", product.Id)
                            <button type="submit">Add to basket</button>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</ul>

Examples/DemoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Action("Summary", "Basket")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Basket", "Index", "Basket")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>